# Generated by Django 5.0 on 2023-12-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('membership_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='RentalApp.admin')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=255)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='RentalApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('Client', models.ManyToManyField(related_name='vehicles', through='RentalApp.ApprovalRequest', to='RentalApp.client')),
            ],
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RentalApp.vehicle'),
        ),
    ]
