# Generated by Django 5.0 on 2023-12-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='pulsar', max_length=255),
            preserve_default=False,
        ),
    ]
